/**
 * Furniture catalog: defines all placeable furniture items.
 * Sprite regions reference furniture-sheet.png (512x1696).
 * Auto-generated by asset-pipeline Stage 5.
 */

export interface SpriteRegion {
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface FurnitureDef {
  id: string;
  label: string;
  category: FurnitureCategory;
  widthCells: number;
  heightCells: number;
  sprite: SpriteRegion;
  /** Override spritesheet path (default: furniture-sheet.png) */
  sheetPath?: string;
  canPlaceOnWalls?: boolean;
  isSeat?: boolean;
  isDesk?: boolean;
  /** 걸어갈 수 있는 footprint 내부 셀 offset (col,row). 지정 시 해당 셀은 grid 점유 안 함.
   *  L자 책상처럼 footprint는 크지만 일부는 실제 투명/빈 공간일 때 사용. */
  walkableCells?: Array<[number, number]>;
}

export type FurnitureCategory = "accessory" | "appliance" | "board" | "chair" | "desk" | "divider" | "floor_decor" | "floor_tile" | "partition" | "plant" | "seating" | "storage" | "wall_decor" | "wall_tile";

/** Categories that characters can walk through/over
 *  (wall_tile 제외 — 벽은 통과 불가) */
export const WALKABLE_CATEGORIES = new Set<FurnitureCategory>([
  "chair", "seating", "floor_tile", "wall_decor", "floor_decor", "accessory",
]);

export const FURNITURE_CATEGORIES: { id: FurnitureCategory; label: string }[] = [
  { id: "accessory", label: "Accessory" },
  { id: "appliance", label: "Appliance" },
  { id: "board", label: "Board" },
  { id: "chair", label: "Chair" },
  { id: "desk", label: "Desk" },
  { id: "divider", label: "Divider" },
  { id: "floor_decor", label: "Floor Decor" },
  { id: "floor_tile", label: "Floor Tile" },
  { id: "partition", label: "Partition" },
  { id: "plant", label: "Plant" },
  { id: "seating", label: "Seating" },
  { id: "storage", label: "Storage" },
  { id: "wall_decor", label: "Wall Decor" },
  { id: "wall_tile", label: "Wall Tile" },
];

export const FURNITURE_CATALOG: FurnitureDef[] = [
  { id: "cubicle_panel_beige", label: "Cubicle Left (Beige)", category: "desk", widthCells: 1, heightCells: 4, sprite: { x: 0, y: 0, w: 32, h: 128 } },
  { id: "cubicle_desk_beige", label: "Cubicle Desk (Beige)", category: "desk", widthCells: 3, heightCells: 3, sprite: { x: 32, y: 0, w: 96, h: 96 }, isDesk: true },
  { id: "cubicle_panel_narrow_beige", label: "Cubicle Panel Narrow (Beige)", category: "desk", widthCells: 1, heightCells: 4, sprite: { x: 128, y: 0, w: 32, h: 128 }, isDesk: true },
  { id: "cubicle_desk_tan", label: "Cubicle Desk (Tan)", category: "desk", widthCells: 3, heightCells: 3, sprite: { x: 192, y: 0, w: 96, h: 96 }, isDesk: true },
  { id: "cubicle_panel_narrow_gray", label: "Cubicle Panel Narrow (Gray)", category: "desk", widthCells: 1, heightCells: 4, sprite: { x: 288, y: 0, w: 32, h: 128 }, isDesk: true },
  { id: "cubicle_desk_gray", label: "Cubicle Desk (Gray)", category: "desk", widthCells: 3, heightCells: 3, sprite: { x: 352, y: 0, w: 96, h: 96 }, isDesk: true },
  { id: "wall_art_colorful", label: "Wall Art (Colorful)", category: "wall_decor", widthCells: 1, heightCells: 2, sprite: { x: 480, y: 0, w: 32, h: 64 }, canPlaceOnWalls: true },
  { id: "wall_art_sunset", label: "Wall Art (Sunset)", category: "wall_decor", widthCells: 1, heightCells: 2, sprite: { x: 480, y: 64, w: 32, h: 64 }, canPlaceOnWalls: true },
  { id: "cubicle_panel_yellow", label: "Cubicle Left (Yellow)", category: "desk", widthCells: 1, heightCells: 4, sprite: { x: 0, y: 128, w: 32, h: 128 } },
  { id: "cubicle_desk_yellow", label: "Cubicle Desk (Yellow)", category: "desk", widthCells: 3, heightCells: 3, sprite: { x: 32, y: 128, w: 96, h: 96 }, isDesk: true },
  { id: "cubicle_panel_narrow_lavender", label: "Cubicle Panel Narrow (Lavender)", category: "desk", widthCells: 2, heightCells: 4, sprite: { x: 128, y: 128, w: 64, h: 128 }, isDesk: true },
  { id: "cubicle_desk_lavender", label: "Cubicle Desk (Lavender)", category: "desk", widthCells: 3, heightCells: 3, sprite: { x: 192, y: 128, w: 96, h: 96 }, isDesk: true },
  { id: "potted_plant_tall", label: "Potted Plant (Tall)", category: "plant", widthCells: 1, heightCells: 3, sprite: { x: 192, y: 224, w: 32, h: 96 } },
  // ⬇ 실제는 맥북 (이전 "Printer" 오표기)
  { id: "printer_small", label: "MacBook (Small)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 320, y: 224, w: 32, h: 64 } },
  { id: "printer_large", label: "MacBook (Large)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 352, y: 224, w: 32, h: 64 } },
  // ═════ 한글 라벨 규칙 ═════
  // "의자 뒤" = 실제 뒷모습 → baseZ 3500 (사람 앞, 등받이가 사람을 가림)
  // "의자 앞" = 실제 앞모습 → baseZ -1000 (사람 뒤)
  // "의자 옆" = 실제 옆모습 → baseZ -1000 (사람 뒤)
  { id: "office_chair_front_dark", label: "의자 뒤 (다크)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 32, y: 256, w: 32, h: 64 }, isSeat: true },
  { id: "office_chair_side_dark", label: "의자 앞 (다크)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 64, y: 256, w: 32, h: 64 }, isSeat: true },
  { id: "office_chair_back_dark", label: "의자 앞 (다크 구멍)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 96, y: 256, w: 32, h: 64 }, isSeat: true },
  // ⬇ 실제는 의자 옆모습 — accessory에서 chair로 복구
  { id: "potted_plant_round", label: "의자 옆 (다크 좌)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 128, y: 256, w: 32, h: 64 }, isSeat: true },
  { id: "potted_plant_bushy", label: "의자 옆 (다크 우)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 160, y: 256, w: 32, h: 64 }, isSeat: true },
  { id: "desk_lamp", label: "Desk Lamp", category: "accessory", widthCells: 1, heightCells: 2, sprite: { x: 224, y: 256, w: 32, h: 64 } },
  { id: "dual_monitor_setup", label: "Dual Monitor Setup", category: "appliance", widthCells: 2, heightCells: 2, sprite: { x: 256, y: 256, w: 64, h: 64 } },
  { id: "keyboard", label: "Keyboard", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 256, w: 32, h: 32 } },
  { id: "mouse_pad", label: "Mouse & Pad", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 256, w: 32, h: 32 } },
  { id: "monitor_silver", label: "Monitor (Silver)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 448, y: 256, w: 32, h: 64 } },
  { id: "monitor_dark", label: "Monitor (Dark)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 480, y: 256, w: 32, h: 64 } },
  { id: "stapler", label: "Stapler", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 320, y: 288, w: 32, h: 32 } },
  { id: "pen_holder", label: "Pen Holder", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 352, y: 288, w: 32, h: 32 } },
  // 갈색 의자 복원 — 사용자 규칙(한글 라벨 기준)으로 모호 해소되어 재등록
  { id: "office_chair_side_brown", label: "의자 앞 (브라운)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 64, y: 320, w: 32, h: 64 }, isSeat: true },
  { id: "office_chair_back_brown", label: "의자 앞 (브라운 구멍)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 96, y: 320, w: 32, h: 64 }, isSeat: true },
  // ⬇ 실제는 의자 옆모습 — accessory에서 chair로 복구
  { id: "desk_plant_small", label: "의자 옆 (브라운 좌)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 128, y: 320, w: 32, h: 64 }, isSeat: true },
  { id: "desk_plant_fern", label: "의자 옆 (브라운 우)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 160, y: 320, w: 32, h: 64 }, isSeat: true },
  { id: "trophy_on_stand", label: "Trophy on Stand", category: "accessory", widthCells: 1, heightCells: 2, sprite: { x: 192, y: 320, w: 32, h: 64 } },
  { id: "presentation_easel", label: "Presentation Easel", category: "board", widthCells: 1, heightCells: 2, sprite: { x: 224, y: 320, w: 32, h: 64 }, canPlaceOnWalls: true },
  { id: "wide_monitor", label: "Wide Monitor", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 256, y: 320, w: 32, h: 64 } },
  { id: "wall_mounted_tv", label: "Wall-mounted TV", category: "appliance", widthCells: 2, heightCells: 2, sprite: { x: 288, y: 320, w: 64, h: 64 }, canPlaceOnWalls: true },
  // ⬇ 실제는 흰색 키보드 (이전 "Copier" 오표기)
  { id: "copier", label: "White Keyboard", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 320, w: 32, h: 32 } },
  { id: "desktop_printer", label: "Desktop Printer", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 320, w: 32, h: 32 } },
  { id: "desktop_pc_beige", label: "Desktop PC (Beige)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 448, y: 320, w: 32, h: 64 } },
  { id: "desktop_pc_gray", label: "Desktop PC (Gray)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 480, y: 320, w: 32, h: 64 } },
  { id: "wall_shelf", label: "Wall Shelf", category: "storage", widthCells: 2, heightCells: 1, sprite: { x: 352, y: 352, w: 64, h: 32 } },
  { id: "wall_art_pair", label: "Wall Art Pair", category: "wall_decor", widthCells: 2, heightCells: 2, sprite: { x: 0, y: 384, w: 64, h: 64 }, canPlaceOnWalls: true },
  { id: "wall_art_abstract", label: "Wall Art (Abstract)", category: "wall_decor", widthCells: 1, heightCells: 2, sprite: { x: 64, y: 384, w: 32, h: 64 }, canPlaceOnWalls: true },
  { id: "diploma_frame_a", label: "Diploma Frame (A)", category: "wall_decor", widthCells: 1, heightCells: 1, sprite: { x: 96, y: 384, w: 32, h: 32 }, canPlaceOnWalls: true },
  { id: "diploma_frame_b", label: "Diploma Frame (B)", category: "wall_decor", widthCells: 1, heightCells: 1, sprite: { x: 128, y: 384, w: 32, h: 32 }, canPlaceOnWalls: true },
  { id: "award_frame", label: "Award Frame", category: "wall_decor", widthCells: 1, heightCells: 1, sprite: { x: 160, y: 384, w: 32, h: 32 }, canPlaceOnWalls: true },
  { id: "bookshelf_tall", label: "Bookshelf (Tall)", category: "storage", widthCells: 1, heightCells: 3, sprite: { x: 192, y: 384, w: 32, h: 96 } },
  { id: "bookshelf_wide", label: "Bookshelf (Wide)", category: "storage", widthCells: 2, heightCells: 3, sprite: { x: 224, y: 384, w: 64, h: 96 } },
  { id: "bulletin_board", label: "Bulletin Board", category: "board", widthCells: 2, heightCells: 2, sprite: { x: 288, y: 384, w: 64, h: 64 }, canPlaceOnWalls: true },
  { id: "desk_phone", label: "Monitor Dark Left", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 384, w: 32, h: 32 } },
  { id: "document_tray", label: "Document Tray", category: "storage", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 384, w: 32, h: 32 } },
  { id: "binder_set", label: "Binder Set", category: "storage", widthCells: 1, heightCells: 1, sprite: { x: 480, y: 384, w: 32, h: 32 } },
  { id: "coffee_mug_blue", label: "Coffee Mug (Blue)", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 96, y: 416, w: 32, h: 32 } },
  { id: "coffee_mug_green", label: "Coffee Mug (Green)", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 128, y: 416, w: 32, h: 32 } },
  { id: "coffee_mug_yellow", label: "Coffee Mug (Yellow)", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 160, y: 416, w: 32, h: 32 } },
  { id: "desktop_globe", label: "Desktop Globe", category: "accessory", widthCells: 1, heightCells: 2, sprite: { x: 352, y: 416, w: 32, h: 64 } },
  // ⬇ 실제는 마우스 (id와 label 불일치 정정)
  { id: "mouse_white", label: "Mouse (White)", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 416, w: 32, h: 32 } },
  { id: "mouse_gray", label: "Mouse (Gray)", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 416, w: 32, h: 32 } },
  { id: "coffee_cup", label: "Coffee Cup", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 480, y: 416, w: 32, h: 32 } },
  // ⬇ 서류 책상 — sprite를 좌측 1×2 로 크롭 (원본은 2×2에 다른 아이템 3개가 뭉쳐있어 배경처럼 보였음)
  { id: "floor_cushion_set", label: "서류 책상", category: "desk", widthCells: 1, heightCells: 2, sprite: { x: 0, y: 448, w: 32, h: 64 }, isDesk: true },
  // ⬇ Office Stool — chair에서 accessory로 이동 (앉는 기능 없음)
  { id: "office_stool", label: "Office Stool", category: "accessory", widthCells: 1, heightCells: 2, sprite: { x: 32, y: 448, w: 32, h: 64 } },
  { id: "armchair", label: "Paper Stack", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 64, y: 448, w: 32, h: 64 } },
  { id: "sofa_gray", label: "Dashboard 1", category: "wall_decor", widthCells: 2, heightCells: 2, sprite: { x: 288, y: 448, w: 64, h: 64 } },
  { id: "paper_clip_holder", label: "Paper Clip Holder", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 448, w: 32, h: 32 } },
  { id: "glass_partition", label: "Glass Partition", category: "partition", widthCells: 2, heightCells: 3, sprite: { x: 224, y: 480, w: 64, h: 96 } },
  // floor_lamp 삭제 — coat_rack(Floor Stand)이 대체 (2026-04-17)
  // ⬇ 실제는 정수기 (이전 "Globe on Stand" 오표기)
  { id: "globe_on_stand", label: "Water Cooler", category: "floor_decor", widthCells: 1, heightCells: 3, sprite: { x: 384, y: 480, w: 32, h: 96 } },
  { id: "desk_divider_blue", label: "Laptop Left", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 416, y: 480, w: 32, h: 64 } },
  { id: "desk_divider_gray", label: "Leftop Front", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 448, y: 480, w: 32, h: 64 } },
  { id: "desk_divider_patterned", label: "Leftop Right", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 480, y: 480, w: 32, h: 64 } },
  // ⬇ 실제는 스탠드(조명) — 옷걸이 아님
  // ⬇ 스탠드 — accessory로 이동 (책상 위 배치 가능). deskTopPrefixes에 이미 등록됨
  { id: "coat_rack", label: "Floor Stand", category: "accessory", widthCells: 1, heightCells: 2, sprite: { x: 320, y: 512, w: 32, h: 64 } },
  { id: "filing_cabinet_dark_a", label: "Filing Cabinet (Dark A)", category: "storage", widthCells: 2, heightCells: 2, sprite: { x: 0, y: 544, w: 64, h: 64 } },
  // L-Desk 3x3 footprint 중 1칸 walkable — 사람이 ㄱ자 안쪽으로 들어가도록
  { id: "l_desk_brown", label: "L-Desk (Brown)", category: "desk", widthCells: 3, heightCells: 3, sprite: { x: 64, y: 544, w: 96, h: 96 }, isDesk: true, walkableCells: [[2, 2]] },
  { id: "desk_phone_a", label: "Desk Phone (A)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 352, y: 544, w: 32, h: 64 } },
  { id: "pc_tower_beige", label: "PC Tower (Beige)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 416, y: 544, w: 32, h: 64 } },
  { id: "pc_tower_gray", label: "PC Tower (Gray)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 448, y: 544, w: 32, h: 64 } },
  { id: "pc_tower_dark", label: "PC Tower (Dark)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 480, y: 544, w: 32, h: 64 } },
  { id: "desk_side_beige", label: "Desk Side (Beige)", category: "desk", widthCells: 1, heightCells: 2, sprite: { x: 160, y: 576, w: 32, h: 64 } },
  { id: "desk_top_beige", label: "Desk Top (Beige)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 192, y: 576, w: 64, h: 64 }, isDesk: true },
  { id: "filing_cabinet_dark_b", label: "Filing Cabinet (Dark B)", category: "storage", widthCells: 2, heightCells: 2, sprite: { x: 0, y: 608, w: 64, h: 64 } },
  { id: "desk_phone_b", label: "Desk Phone (B)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 352, y: 608, w: 32, h: 64 } },
  { id: "book_shelf_row_a", label: "Book Shelf Row (A)", category: "storage", widthCells: 2, heightCells: 1, sprite: { x: 384, y: 608, w: 64, h: 32 } },
  { id: "book_shelf_row_b", label: "Book Shelf Row (B)", category: "storage", widthCells: 2, heightCells: 1, sprite: { x: 448, y: 608, w: 64, h: 32 } },
  // L-Desk 3x3 footprint 중 1칸 walkable (방향 반대 — ㄴ자 안쪽)
  { id: "l_desk_beige", label: "L-Desk (Beige)", category: "desk", widthCells: 3, heightCells: 3, sprite: { x: 64, y: 640, w: 96, h: 96 }, isDesk: true, walkableCells: [[0, 2]] },
  { id: "desk_side_tan", label: "Desk Side (Tan)", category: "desk", widthCells: 1, heightCells: 2, sprite: { x: 160, y: 640, w: 32, h: 64 } },
  { id: "desk_top_tan", label: "Desk Top (Tan)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 192, y: 640, w: 64, h: 64 }, isDesk: true },
  { id: "desk_top_orange", label: "Desk Top (Orange)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 384, y: 640, w: 64, h: 64 }, isDesk: true },
  { id: "desk_top_wood", label: "Desk Top (Wood)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 448, y: 640, w: 64, h: 64 }, isDesk: true },
  { id: "filing_cabinet_side", label: "Filing Cabinet (Side)", category: "storage", widthCells: 1, heightCells: 2, sprite: { x: 0, y: 672, w: 32, h: 64 } },
  { id: "desk_phone_c", label: "Desk Phone (C)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 352, y: 672, w: 32, h: 64 } },
  { id: "desk_side_lavender", label: "Desk Side (Lavender)", category: "desk", widthCells: 1, heightCells: 2, sprite: { x: 160, y: 704, w: 32, h: 64 } },
  { id: "desk_top_lavender", label: "Desk Top (Lavender)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 192, y: 704, w: 64, h: 64 }, isDesk: true },
  { id: "desk_extension_lavender_a", label: "Desk Extension (Lavender A)", category: "desk", widthCells: 1, heightCells: 2, sprite: { x: 256, y: 704, w: 32, h: 64 } },
  { id: "desk_extension_lavender_b", label: "Desk Extension (Lavender B)", category: "desk", widthCells: 1, heightCells: 2, sprite: { x: 288, y: 704, w: 32, h: 64 } },
  { id: "desk_extension_lavender_c", label: "Desk Extension (Lavender C)", category: "desk", widthCells: 1, heightCells: 2, sprite: { x: 320, y: 704, w: 32, h: 64 } },
  { id: "desk_l_shape_orange", label: "Desk L-Shape (Orange)", category: "desk", widthCells: 2, heightCells: 3, sprite: { x: 384, y: 704, w: 64, h: 96 }, isDesk: true },
  { id: "desk_bottom_wood", label: "Desk Bottom (Wood)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 448, y: 704, w: 64, h: 64 }, isDesk: true },
  { id: "sofa_left_dark", label: "Dispenser", category: "appliance", widthCells: 2, heightCells: 3, sprite: { x: 0, y: 736, w: 64, h: 96 }, isSeat: true },
  { id: "sofa_right_dark", label: "Dispenser Full", category: "appliance", widthCells: 2, heightCells: 3, sprite: { x: 64, y: 736, w: 64, h: 96 }, isSeat: true },
  { id: "desk_phone_d", label: "Desk Phone (D)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 352, y: 736, w: 32, h: 64 } },
  { id: "desk_double_beige", label: "Dispenser Full 2", category: "appliance", widthCells: 2, heightCells: 2, sprite: { x: 128, y: 768, w: 64, h: 64 }, isDesk: true },
  { id: "desk_module_a", label: "Desk Module (A)", category: "desk", widthCells: 1, heightCells: 2, sprite: { x: 256, y: 768, w: 32, h: 64 } },
  { id: "desk_module_b", label: "Desk Module (B)", category: "desk", widthCells: 1, heightCells: 2, sprite: { x: 288, y: 768, w: 32, h: 64 } },
  { id: "desk_module_c", label: "Desk Module (C)", category: "desk", widthCells: 1, heightCells: 2, sprite: { x: 320, y: 768, w: 32, h: 64 } },
  { id: "glass_partition_long", label: "Glass Partition (Long)", category: "partition", widthCells: 7, heightCells: 3, sprite: { x: 0, y: 832, w: 224, h: 96 } },
  { id: "monitor_arm_setup", label: "Monitor Arm Setup", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 320, y: 832, w: 32, h: 64 } },
  { id: "desk_with_pc", label: "Desk with PC", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 352, y: 832, w: 64, h: 64 }, isDesk: true },
  { id: "conference_table_beige", label: "Conference Table (Beige)", category: "desk", widthCells: 3, heightCells: 2, sprite: { x: 224, y: 896, w: 96, h: 64 }, isDesk: true },
  { id: "conference_table_brown", label: "Conference Table (Brown)", category: "desk", widthCells: 3, heightCells: 2, sprite: { x: 320, y: 896, w: 96, h: 64 }, isDesk: true },
  { id: "conference_table_end", label: "Conference Table End", category: "desk", widthCells: 1, heightCells: 2, sprite: { x: 416, y: 896, w: 32, h: 64 }, isDesk: true },
  { id: "corner_workstation", label: "Corner Workstation", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 448, y: 896, w: 64, h: 64 } },
  { id: "mouse_standalone", label: "Mouse (Standalone)", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 928, w: 32, h: 32 } },
  { id: "long_table_lavender", label: "Conference Table (Lavender)", category: "desk", widthCells: 3, heightCells: 2, sprite: { x: 32, y: 960, w: 96, h: 64 }, isDesk: true },
  { id: "long_table_tan", label: "Conference Table (Tan)", category: "desk", widthCells: 3, heightCells: 2, sprite: { x: 128, y: 960, w: 96, h: 64 }, isDesk: true },
  { id: "long_table_beige", label: "Conference Table (Beige)", category: "desk", widthCells: 3, heightCells: 2, sprite: { x: 224, y: 960, w: 96, h: 64 }, isDesk: true },
  { id: "desk_with_monitors", label: "Desk with Monitors", category: "desk", widthCells: 3, heightCells: 2, sprite: { x: 320, y: 960, w: 96, h: 64 }, isDesk: true },
  { id: "tape_dispenser", label: "Tape Dispenser", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 960, w: 32, h: 32 } },
  { id: "office_supply_set", label: "Office Supply Set", category: "accessory", widthCells: 2, heightCells: 1, sprite: { x: 448, y: 960, w: 64, h: 32 } },
  { id: "pencil_sharpener", label: "Pencil Sharpener", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 992, w: 32, h: 32 } },
  { id: "calculator_a", label: "Calculator (A)", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 992, w: 32, h: 32 } },
  { id: "calculator_b", label: "Calculator (B)", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 480, y: 992, w: 32, h: 32 } },
  { id: "desk_combo_with_monitors", label: "Desk Combo with Monitors", category: "desk", widthCells: 3, heightCells: 2, sprite: { x: 320, y: 1024, w: 96, h: 64 }, isDesk: true },
  { id: "stamp", label: "Stamp", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 1024, w: 32, h: 32 } },
  { id: "ink_pad", label: "Ink Pad", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 1024, w: 32, h: 32 } },
  { id: "paper_weight", label: "Paper Weight", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 480, y: 1024, w: 32, h: 32 } },
  { id: "workstation_large", label: "Workstation (Large)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 448, y: 1056, w: 64, h: 64 }, isDesk: true },
  { id: "desk_pillar_a", label: "Desk Pillar (A)", category: "desk", widthCells: 1, heightCells: 3, sprite: { x: 224, y: 1088, w: 32, h: 96 } },
  { id: "office_desk_setup_a", label: "Office Desk Setup (A)", category: "desk", widthCells: 1, heightCells: 2, sprite: { x: 256, y: 1088, w: 32, h: 64 }, isDesk: true },
  { id: "office_desk_setup_b", label: "Office Desk Setup (B)", category: "desk", widthCells: 1, heightCells: 2, sprite: { x: 288, y: 1088, w: 32, h: 64 }, isDesk: true },
  { id: "office_desk_setup_compact", label: "Office Desk Setup (Compact)", category: "desk", widthCells: 1, heightCells: 2, sprite: { x: 416, y: 1088, w: 32, h: 64 } },
  { id: "tall_cabinet_a", label: "Tall Cabinet (A)", category: "storage", widthCells: 1, heightCells: 3, sprite: { x: 320, y: 1120, w: 32, h: 96 } },
  { id: "tall_cabinet_b", label: "Tall Cabinet (B)", category: "storage", widthCells: 1, heightCells: 3, sprite: { x: 352, y: 1120, w: 32, h: 96 } },
  { id: "document_stack_a", label: "Document Stack (A)", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 1120, w: 32, h: 32 } },
  { id: "document_stack_b", label: "Document Stack (B)", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 1120, w: 32, h: 32 } },
  { id: "document_stack_c", label: "Document Stack (C)", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 480, y: 1120, w: 32, h: 32 } },
  { id: "pen_a", label: "Pen (A)", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 288, y: 1152, w: 32, h: 32 } },
  { id: "pen_b", label: "Pen (B)", category: "accessory", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 1152, w: 32, h: 32 } },
  { id: "pc_tower_black", label: "PC Tower (Black)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 416, y: 1152, w: 32, h: 64 } },
  { id: "desk_edge_b", label: "Desk Edge (B)", category: "desk", widthCells: 1, heightCells: 3, sprite: { x: 224, y: 1184, w: 32, h: 96 } },
  { id: "usb_drive_a", label: "USB Drive (A)", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 256, y: 1184, w: 32, h: 32 } },
  { id: "usb_drive_b", label: "USB Drive (B)", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 288, y: 1184, w: 32, h: 32 } },
  { id: "medium_desk_tan", label: "Medium Desk (Tan)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 160, y: 1216, w: 64, h: 64 }, isDesk: true },
  { id: "workstation_setup_a", label: "Workstation Setup (A)", category: "desk", widthCells: 2, heightCells: 3, sprite: { x: 256, y: 1216, w: 64, h: 96 }, isDesk: true },
  { id: "workstation_setup_b", label: "Workstation Setup (B)", category: "desk", widthCells: 2, heightCells: 3, sprite: { x: 320, y: 1216, w: 64, h: 96 }, isDesk: true },
  { id: "workstation_setup_c", label: "Workstation Setup (C)", category: "desk", widthCells: 2, heightCells: 3, sprite: { x: 384, y: 1216, w: 64, h: 96 }, isDesk: true },
  // clipboard_a/b 삭제 — 실제는 의자 옆모습이며 potted_plant_round/bushy와 중복 (2026-04-17)
  { id: "small_monitor_a", label: "Small Monitor (A)", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 256, y: 1408, w: 32, h: 32 } },
  // ⬇ 실제는 듀얼모니터 (이전 "Backpack" 오표기)
  { id: "backpack_blue", label: "Dual Monitor (Blue)", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 288, y: 1408, w: 32, h: 32 } },
  // ⬇ 실제는 듀얼모니터 + 모니터암 (이전 "3 Monitors" 오표기) — 우선순위/배경 이슈 모니터링 대상
  { id: "backpack_teal", label: "Monitor Arm Setup (White)", category: "appliance", widthCells: 1, heightCells: 3, sprite: { x: 320, y: 1408, w: 32, h: 96 } },
  { id: "water_dispenser", label: "Monitor Arm Setup (Dark)", category: "appliance", widthCells: 1, heightCells: 3, sprite: { x: 352, y: 1408, w: 32, h: 96 } },
  { id: "backpack_orange", label: "Dual Monitor (Orange)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 256, y: 1440, w: 32, h: 64 } },
  { id: "backpack_brown", label: "Dual Monitor (Brown)", category: "appliance", widthCells: 1, heightCells: 2, sprite: { x: 288, y: 1440, w: 32, h: 64 } },
  { id: "key_card", label: "Key Card", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 1440, w: 32, h: 32 } },
  { id: "small_monitor_b", label: "Desk Phone", category: "appliance", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 1472, w: 32, h: 32 } },
  { id: "suitcase_blue", label: "Suitcase (Blue)", category: "floor_decor", widthCells: 1, heightCells: 2, sprite: { x: 256, y: 1504, w: 32, h: 64 } },
  { id: "suitcase_red", label: "Suitcase (Red)", category: "floor_decor", widthCells: 1, heightCells: 2, sprite: { x: 288, y: 1504, w: 32, h: 64 } },
  { id: "suitcase_orange", label: "Suitcase (Orange)", category: "floor_decor", widthCells: 1, heightCells: 2, sprite: { x: 320, y: 1504, w: 32, h: 64 } },
  { id: "suitcase_brown", label: "Suitcase (Brown)", category: "floor_decor", widthCells: 1, heightCells: 2, sprite: { x: 352, y: 1504, w: 32, h: 64 } },
  { id: "suitcase_teal", label: "Suitcase (Teal)", category: "floor_decor", widthCells: 1, heightCells: 2, sprite: { x: 384, y: 1504, w: 32, h: 64 } },
  { id: "suitcase_green", label: "Suitcase (Green)", category: "floor_decor", widthCells: 1, heightCells: 2, sprite: { x: 416, y: 1504, w: 32, h: 64 } },
  { id: "trash_can_gray", label: "Trash Can (Gray)", category: "floor_decor", widthCells: 1, heightCells: 2, sprite: { x: 256, y: 1568, w: 32, h: 64 } },
  { id: "trash_can_blue", label: "Trash Can (Blue)", category: "floor_decor", widthCells: 1, heightCells: 2, sprite: { x: 288, y: 1568, w: 32, h: 64 } },
  { id: "trash_can_green", label: "Trash Can (Green)", category: "floor_decor", widthCells: 1, heightCells: 2, sprite: { x: 320, y: 1568, w: 32, h: 64 } },
  { id: "trash_can_brown", label: "Trash Can (Brown)", category: "floor_decor", widthCells: 1, heightCells: 2, sprite: { x: 352, y: 1568, w: 32, h: 64 } },
  { id: "plant_arrangement", label: "Plant Arrangement", category: "plant", widthCells: 2, heightCells: 2, sprite: { x: 384, y: 1568, w: 64, h: 64 } },
  { id: "cubicle_panel_narrow_tan", label: "Cubicle Panel Narrow (Tan)", category: "desk", widthCells: 1, heightCells: 4, sprite: { x: 160, y: 0, w: 32, h: 128 }, isDesk: true },
  { id: "cubicle_panel_narrow_dark_gray", label: "Cubicle Panel Narrow (Dark Gray)", category: "desk", widthCells: 1, heightCells: 4, sprite: { x: 320, y: 0, w: 32, h: 128 }, isDesk: true },
  { id: "desk_module_d", label: "Desk Module (D)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 256, y: 576, w: 64, h: 64 } },
  { id: "desk_module_e", label: "Desk Module (E)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 256, y: 640, w: 64, h: 64 } },
  { id: "filing_cabinet_top", label: "Air Conditioner", category: "wall_decor", widthCells: 2, heightCells: 1, sprite: { x: 352, y: 384, w: 64, h: 32 } },
  { id: "desk_organizer", label: "Desk Organizer", category: "storage", widthCells: 1, heightCells: 2, sprite: { x: 384, y: 416, w: 32, h: 64 } },
  // carpet_swatch_strip 삭제 — 실제는 책상이라 desk 카테고리와 중복 (2026-04-17)
  { id: "carpet_tile_red_brown", label: "Carpet Tile (Red-Brown)", category: "floor_decor", widthCells: 1, heightCells: 1, sprite: { x: 320, y: 128, w: 32, h: 32 } },
  { id: "carpet_tile_dark_red", label: "Carpet Tile (Dark Red)", category: "floor_decor", widthCells: 1, heightCells: 1, sprite: { x: 352, y: 128, w: 32, h: 32 } },
  { id: "carpet_tile_maroon", label: "Carpet Tile (Maroon)", category: "floor_decor", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 128, w: 32, h: 32 } },
  { id: "carpet_tile_gray_brown", label: "Carpet Tile (Gray-Brown)", category: "floor_decor", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 160, w: 32, h: 32 } },
  { id: "carpet_tile_brown", label: "Carpet Tile (Brown)", category: "floor_decor", widthCells: 1, heightCells: 1, sprite: { x: 352, y: 160, w: 32, h: 32 } },
  { id: "carpet_tile_tan", label: "Carpet Tile (Tan)", category: "floor_decor", widthCells: 1, heightCells: 1, sprite: { x: 320, y: 160, w: 32, h: 32 } },
  { id: "carpet_tile_light_gray", label: "Carpet Tile (Light Gray)", category: "floor_decor", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 160, w: 32, h: 32 } },
  { id: "carpet_tile_off_white", label: "Carpet Tile (Off-White)", category: "floor_decor", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 160, w: 32, h: 32 } },
  { id: "carpet_tile_white", label: "Carpet Tile (White)", category: "floor_decor", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 128, w: 32, h: 32 } },
  { id: "carpet_tile_pale_gray", label: "Carpet Tile (Pale Gray)", category: "floor_decor", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 128, w: 32, h: 32 } },
  // 갈색 front-left/right 복원 — 실제 뒷모습 (사람 앞에 렌더)
  { id: "office_chair_front_left_brown", label: "의자 뒤 (브라운 좌)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 0, y: 320, w: 32, h: 64 }, isSeat: true },
  { id: "office_chair_front_right_brown", label: "의자 뒤 (브라운 우)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 32, y: 320, w: 32, h: 64 }, isSeat: true },
  { id: "office_chair_front_left_dark", label: "의자 뒤 (다크 좌)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 0, y: 256, w: 32, h: 64 }, isSeat: true },
  { id: "swivel_chair_blue", label: "회전의자 앞 (Blue)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 96, y: 480, w: 32, h: 64 }, isSeat: true },
  { id: "swivel_chair_green", label: "회전의자 앞 (Green)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 128, y: 480, w: 32, h: 64 }, isSeat: true },
  { id: "swivel_chair_yellow", label: "회전의자 앞 (Yellow)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 160, y: 480, w: 32, h: 64 }, isSeat: true },
  { id: "swivel_chair_gold", label: "회전의자 앞 (Gold)", category: "chair", widthCells: 1, heightCells: 2, sprite: { x: 192, y: 480, w: 32, h: 64 }, isSeat: true },
  { id: "meeting_table_small", label: "Deskterior 1", category: "appliance", widthCells: 3, heightCells: 2, sprite: { x: 224, y: 832, w: 96, h: 64 } },
  { id: "dual_workstation", label: "Dual Workstation", category: "desk", widthCells: 3, heightCells: 2, sprite: { x: 416, y: 832, w: 96, h: 64 } },
  { id: "monitor_pair_a", label: "Print Machine 1", category: "appliance", widthCells: 2, heightCells: 2, sprite: { x: 384, y: 1312, w: 64, h: 64 } },
  { id: "monitor_pair_b", label: "Print Machine 2", category: "appliance", widthCells: 2, heightCells: 2, sprite: { x: 320, y: 1312, w: 64, h: 64 } },
  { id: "monitor_pair_c", label: "Print Machine 3", category: "appliance", widthCells: 2, heightCells: 2, sprite: { x: 256, y: 1312, w: 64, h: 64 } },
  // ⬇ 실제는 전화기 (이전 "Briefcase" 오표기)
  { id: "briefcase", label: "Desk Phone", category: "accessory", widthCells: 1, heightCells: 2, sprite: { x: 416, y: 1440, w: 32, h: 64 } },
  { id: "office_supply_box_a", label: "Office Supply Box (A)", category: "accessory", widthCells: 2, heightCells: 2, sprite: { x: 448, y: 1344, w: 64, h: 64 } },
  { id: "office_supply_box_b", label: "Office Supply Box (B)", category: "accessory", widthCells: 2, heightCells: 2, sprite: { x: 448, y: 1280, w: 64, h: 64 } },
  { id: "office_supply_box_c", label: "Office Supply Box (C)", category: "accessory", widthCells: 2, heightCells: 2, sprite: { x: 448, y: 1216, w: 64, h: 64 } },
  { id: "desk_corner_tan", label: "Desk Corner (Tan)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 160, y: 1120, w: 64, h: 64 } },
  { id: "desk_front_tan_beige", label: "Desk Front (Tan-Beige)", category: "desk", widthCells: 2, heightCells: 1, sprite: { x: 128, y: 1088, w: 64, h: 32 } },
  { id: "desk_front_lavender", label: "Desk Front (Lavender)", category: "desk", widthCells: 2, heightCells: 1, sprite: { x: 128, y: 1184, w: 64, h: 32 } },
  { id: "desk_side_panel_lavender", label: "Desk Side Panel (Lavender)", category: "desk", widthCells: 1, heightCells: 3, sprite: { x: 96, y: 1184, w: 32, h: 96 } },
  { id: "desk_corner_lavender", label: "Desk Corner (Lavender)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 32, y: 1216, w: 64, h: 64 } },
  { id: "desk_front_gray", label: "Desk Front (Gray)", category: "desk", widthCells: 2, heightCells: 1, sprite: { x: 0, y: 1184, w: 64, h: 32 } },
  { id: "desk_corner_beige_tan", label: "Desk Corner (Beige-Tan)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 32, y: 1120, w: 64, h: 64 } },
  { id: "desk_front_dark", label: "Desk Front (Dark)", category: "desk", widthCells: 2, heightCells: 1, sprite: { x: 0, y: 1088, w: 64, h: 32 } },
  { id: "desk_side_panel_beige", label: "Desk Side Panel (Beige)", category: "desk", widthCells: 1, heightCells: 3, sprite: { x: 96, y: 1088, w: 32, h: 96 } },
  { id: "desk_side_panel_gray_beige", label: "Desk Side Panel (Gray-Beige)", category: "desk", widthCells: 1, heightCells: 3, sprite: { x: 0, y: 1376, w: 32, h: 96 } },
  { id: "desk_side_panel_tan", label: "Desk Side Panel (Tan)", category: "desk", widthCells: 1, heightCells: 3, sprite: { x: 96, y: 1280, w: 32, h: 96 } },
  { id: "desk_front_beige_gray", label: "Desk Front (Beige-Gray)", category: "desk", widthCells: 2, heightCells: 1, sprite: { x: 0, y: 1280, w: 64, h: 32 } },
  { id: "desk_corner_gray", label: "Desk Corner (Gray)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 32, y: 1312, w: 64, h: 64 } },
  { id: "desk_side_panel_brown", label: "Desk Side Panel (Brown)", category: "desk", widthCells: 1, heightCells: 3, sprite: { x: 128, y: 1376, w: 32, h: 96 } },
  { id: "desk_corner_brown", label: "Desk Corner (Brown)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 160, y: 1408, w: 64, h: 64 } },
  { id: "desk_front_brown", label: "Desk Front (Brown)", category: "desk", widthCells: 2, heightCells: 1, sprite: { x: 192, y: 1376, w: 64, h: 32 } },
  { id: "desk_front_lavender_gray", label: "Desk Front (Lavender-Gray)", category: "desk", widthCells: 2, heightCells: 1, sprite: { x: 192, y: 1472, w: 64, h: 32 } },
  { id: "desk_corner_lavender_gray", label: "Desk Corner (Lavender-Gray)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 160, y: 1504, w: 64, h: 64 } },
  { id: "desk_side_panel_lavender_gray", label: "Desk Side Panel (Lavender-Gray)", category: "desk", widthCells: 1, heightCells: 3, sprite: { x: 128, y: 1472, w: 32, h: 96 } },
  { id: "desk_side_panel_gray", label: "Desk Side Panel (Gray)", category: "desk", widthCells: 1, heightCells: 3, sprite: { x: 0, y: 1472, w: 32, h: 96 } },
  { id: "desk_corner_gray_dark", label: "Desk Corner (Gray-Dark)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 32, y: 1504, w: 64, h: 64 } },
  { id: "desk_corner_beige_light", label: "Desk Corner (Beige-Light)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 32, y: 1408, w: 64, h: 64 } },
  { id: "desk_front_light", label: "Desk Front (Light)", category: "desk", widthCells: 2, heightCells: 1, sprite: { x: 64, y: 1472, w: 64, h: 32 } },
  { id: "desk_front_beige_light", label: "Desk Front (Beige-Light)", category: "desk", widthCells: 2, heightCells: 1, sprite: { x: 64, y: 1376, w: 64, h: 32 } },
  { id: "desk_side_panel_dark_gray", label: "Desk Side Panel (Dark Gray)", category: "desk", widthCells: 1, heightCells: 3, sprite: { x: 0, y: 1568, w: 32, h: 96 } },
  { id: "desk_corner_dark_gray", label: "Desk Corner (Dark Gray)", category: "desk", widthCells: 2, heightCells: 2, sprite: { x: 32, y: 1600, w: 64, h: 64 } },
  { id: "desk_front_dark_gray", label: "Desk Front (Dark Gray)", category: "desk", widthCells: 2, heightCells: 1, sprite: { x: 64, y: 1568, w: 64, h: 32 } },
  { id: "cubicle_panel_dark_gray", label: "Cubicle Long (Dark Gray)", category: "desk", widthCells: 1, heightCells: 4, sprite: { x: 448, y: 0, w: 32, h: 128 } },

];

// === Room Builder tiles (wall, floor, divider) ===
// Generated from detected-assets.json — all 115 approved items + dividers
const ROOM_BUILDER_SHEET = "/assets/teammaker/tiles/office/Room_Builder_Office_32x32.png";
export const TM_FURNITURE_SHEET = "/assets/teammaker/tiles/office/furniture-sheet.png";

const ROOM_BUILDER_RAW: Omit<FurnitureDef, "sheetPath" | "canPlaceOnWalls">[] = [
  { id: "wall_lavender_A_tl", label: "Wall Lavender A: Top-Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 192, w: 32, h: 32 } },
  { id: "wall_lavender_A_t", label: "Wall Lavender A: Top", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 32, y: 192, w: 32, h: 32 } },
  { id: "wall_lavender_A_tr", label: "Wall Lavender A: Top-Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 64, y: 192, w: 32, h: 32 } },
  { id: "wall_lavender_A_l", label: "Wall Lavender A: Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 224, w: 32, h: 32 } },
  { id: "wall_lavender_A_c", label: "Wall Lavender A: Center", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 32, y: 224, w: 32, h: 32 } },
  { id: "wall_lavender_A_r", label: "Wall Lavender A: Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 64, y: 224, w: 32, h: 32 } },
  { id: "wall_lavender_C_tl", label: "Wall Lavender C: Top-Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 224, y: 192, w: 32, h: 32 } },
  { id: "wall_lavender_C_t", label: "Wall Lavender C: Top", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 256, y: 192, w: 32, h: 32 } },
  { id: "wall_lavender_C_tr", label: "Wall Lavender C: Top-Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 288, y: 192, w: 32, h: 32 } },
  { id: "wall_lavender_C_l", label: "Wall Lavender C: Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 224, y: 224, w: 32, h: 32 } },
  { id: "wall_lavender_C_c", label: "Wall Lavender C: Center", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 256, y: 224, w: 32, h: 32 } },
  { id: "wall_lavender_C_r", label: "Wall Lavender C: Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 288, y: 224, w: 32, h: 32 } },
  { id: "floor_lavender_1", label: "Floor Lavender: Stone Tile", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 320, y: 192, w: 32, h: 32 } },
  { id: "floor_lavender_2", label: "Floor Lavender: Marble", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 352, y: 192, w: 32, h: 32 } },
  { id: "floor_lavender_3", label: "Floor Lavender: Herringbone", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 192, w: 32, h: 32 } },
  { id: "floor_lavender_4", label: "Floor Lavender: Checker", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 192, w: 32, h: 32 } },
  { id: "floor_lavender_5", label: "Floor Lavender: Plank A", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 192, w: 32, h: 32 } },
  { id: "floor_lavender_6", label: "Floor Lavender: Plank B", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 480, y: 192, w: 32, h: 32 } },
  { id: "floor_lavender_7", label: "Floor Lavender: Smooth", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 320, y: 224, w: 32, h: 32 } },
  { id: "floor_lavender_8", label: "Floor Lavender: Dotted", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 352, y: 224, w: 32, h: 32 } },
  { id: "floor_lavender_9", label: "Floor Lavender: Diamond", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 224, w: 32, h: 32 } },
  { id: "floor_lavender_10", label: "Floor Lavender: Cross", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 224, w: 32, h: 32 } },
  { id: "floor_lavender_11", label: "Floor Lavender: Brick", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 224, w: 32, h: 32 } },
  { id: "floor_lavender_12", label: "Floor Lavender: Weave", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 480, y: 224, w: 32, h: 32 } },
  { id: "wall_gray_A_tl", label: "Wall Gray A: Top-Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 256, w: 32, h: 32 } },
  { id: "wall_gray_A_t", label: "Wall Gray A: Top", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 32, y: 256, w: 32, h: 32 } },
  { id: "wall_gray_A_tr", label: "Wall Gray A: Top-Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 64, y: 256, w: 32, h: 32 } },
  { id: "wall_gray_A_l", label: "Wall Gray A: Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 288, w: 32, h: 32 } },
  { id: "wall_gray_A_c", label: "Wall Gray A: Center", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 32, y: 288, w: 32, h: 32 } },
  { id: "wall_gray_A_r", label: "Wall Gray A: Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 64, y: 288, w: 32, h: 32 } },
  { id: "wall_gray_C_tl", label: "Wall Gray C: Top-Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 224, y: 256, w: 32, h: 32 } },
  { id: "wall_gray_C_t", label: "Wall Gray C: Top", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 256, y: 256, w: 32, h: 32 } },
  { id: "wall_gray_C_tr", label: "Wall Gray C: Top-Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 288, y: 256, w: 32, h: 32 } },
  { id: "wall_gray_C_l", label: "Wall Gray C: Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 224, y: 288, w: 32, h: 32 } },
  { id: "wall_gray_C_c", label: "Wall Gray C: Center", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 256, y: 288, w: 32, h: 32 } },
  { id: "wall_gray_C_r", label: "Wall Gray C: Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 288, y: 288, w: 32, h: 32 } },
  { id: "floor_gray_1", label: "Floor Gray: Stone Tile", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 320, y: 256, w: 32, h: 32 } },
  { id: "floor_gray_2", label: "Floor Gray: Marble", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 352, y: 256, w: 32, h: 32 } },
  { id: "floor_gray_3", label: "Floor Gray: Herringbone", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 256, w: 32, h: 32 } },
  { id: "floor_gray_4", label: "Floor Gray: Checker", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 256, w: 32, h: 32 } },
  { id: "floor_gray_5", label: "Floor Gray: Plank A", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 256, w: 32, h: 32 } },
  { id: "floor_gray_6", label: "Floor Gray: Plank B", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 480, y: 256, w: 32, h: 32 } },
  { id: "floor_gray_7", label: "Floor Gray: Smooth", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 320, y: 288, w: 32, h: 32 } },
  { id: "floor_gray_8", label: "Floor Gray: Dotted", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 352, y: 288, w: 32, h: 32 } },
  { id: "floor_gray_9", label: "Floor Gray: Diamond", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 288, w: 32, h: 32 } },
  { id: "floor_gray_10", label: "Floor Gray: Cross", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 288, w: 32, h: 32 } },
  { id: "floor_gray_11", label: "Floor Gray: Brick", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 288, w: 32, h: 32 } },
  { id: "floor_gray_12", label: "Floor Gray: Weave", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 480, y: 288, w: 32, h: 32 } },
  { id: "wall_brick_A_tl", label: "Wall Brick A: Top-Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 320, w: 32, h: 32 } },
  { id: "wall_brick_A_t", label: "Wall Brick A: Top", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 32, y: 320, w: 32, h: 32 } },
  { id: "wall_brick_A_tr", label: "Wall Brick A: Top-Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 64, y: 320, w: 32, h: 32 } },
  { id: "wall_brick_A_l", label: "Wall Pink A: Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 352, w: 32, h: 32 } },
  { id: "wall_brick_A_c", label: "Wall Pink A: Center", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 32, y: 352, w: 32, h: 32 } },
  { id: "wall_brick_A_r", label: "Wall Pink A: Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 64, y: 352, w: 32, h: 32 } },
  { id: "wall_brick_C_tl", label: "Wall Brick C: Top-Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 224, y: 320, w: 32, h: 32 } },
  { id: "wall_brick_C_t", label: "Wall Brick C: Top", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 256, y: 320, w: 32, h: 32 } },
  { id: "wall_brick_C_tr", label: "Wall Brick C: Top-Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 288, y: 320, w: 32, h: 32 } },
  { id: "wall_brick_C_l", label: "Wall Pink C: Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 224, y: 352, w: 32, h: 32 } },
  { id: "wall_brick_C_c", label: "Wall Pink C: Center", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 256, y: 352, w: 32, h: 32 } },
  { id: "wall_brick_C_r", label: "Wall Pink C: Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 288, y: 352, w: 32, h: 32 } },
  { id: "floor_brick_1", label: "Floor Brick: Stone Tile", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 320, y: 320, w: 32, h: 32 } },
  { id: "floor_brick_2", label: "Floor Brick: Marble", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 352, y: 320, w: 32, h: 32 } },
  { id: "floor_brick_3", label: "Floor Brick: Herringbone", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 320, w: 32, h: 32 } },
  { id: "floor_brick_4", label: "Floor Brick: Checker", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 320, w: 32, h: 32 } },
  { id: "floor_brick_5", label: "Floor Brick: Plank A", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 320, w: 32, h: 32 } },
  { id: "floor_brick_6", label: "Floor Brick: Plank B", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 480, y: 320, w: 32, h: 32 } },
  { id: "floor_brick_7", label: "Floor Brick: Smooth", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 320, y: 352, w: 32, h: 32 } },
  { id: "floor_brick_8", label: "Floor Brick: Dotted", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 352, y: 352, w: 32, h: 32 } },
  { id: "floor_brick_9", label: "Floor Brick: Diamond", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 352, w: 32, h: 32 } },
  { id: "floor_brick_10", label: "Floor Brick: Cross", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 352, w: 32, h: 32 } },
  { id: "floor_brick_11", label: "Floor Brick: Brick", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 352, w: 32, h: 32 } },
  { id: "floor_brick_12", label: "Floor Brick: Weave", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 480, y: 352, w: 32, h: 32 } },
  { id: "wall_pink_A_tl", label: "Wall Pink A: Top-Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 384, w: 32, h: 32 } },
  { id: "wall_pink_A_t", label: "Wall Pink A: Top", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 32, y: 384, w: 32, h: 32 } },
  { id: "wall_pink_A_tr", label: "Wall Pink A: Top-Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 64, y: 384, w: 32, h: 32 } },
  { id: "wall_pink_C_tl", label: "Wall Pink C: Top-Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 224, y: 384, w: 32, h: 32 } },
  { id: "wall_pink_C_t", label: "Wall Pink C: Top", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 256, y: 384, w: 32, h: 32 } },
  { id: "wall_pink_C_tr", label: "Wall Pink C: Top-Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 288, y: 384, w: 32, h: 32 } },
  { id: "floor_pink_1", label: "Floor Pink: Stone Tile", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 320, y: 384, w: 32, h: 32 } },
  { id: "floor_pink_2", label: "Floor Pink: Marble", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 352, y: 384, w: 32, h: 32 } },
  { id: "floor_pink_3", label: "Floor Pink: Herringbone", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 384, w: 32, h: 32 } },
  { id: "floor_pink_4", label: "Floor Pink: Checker", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 384, w: 32, h: 32 } },
  { id: "floor_pink_5", label: "Floor Pink: Plank A", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 384, w: 32, h: 32 } },
  { id: "floor_pink_6", label: "Floor Pink: Plank B", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 480, y: 384, w: 32, h: 32 } },
  { id: "wall_base_lavender_A_l", label: "Wall Base: Lavender A Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 160, w: 32, h: 32 } },
  { id: "wall_base_lavender_A_c", label: "Wall Base: Lavender A Center", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 32, y: 160, w: 32, h: 32 } },
  { id: "wall_base_lavender_A_r", label: "Wall Base: Lavender A Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 64, y: 160, w: 32, h: 32 } },
  { id: "divider_base_lavender_gap", label: "Divider Base: Lavender Gap", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 96, y: 160, w: 32, h: 32 } },
  { id: "wall_base_lavender_B_l", label: "Wall Base: Lavender B Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 128, y: 160, w: 32, h: 32 } },
  { id: "wall_base_lavender_B_c", label: "Wall Base: Lavender B Center", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 160, y: 160, w: 32, h: 32 } },
  { id: "wall_base_lavender_B_r", label: "Wall Base: Lavender B Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 192, y: 160, w: 32, h: 32 } },
  { id: "wall_base_lavender_C_l", label: "Wall Base: Lavender C Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 224, y: 160, w: 32, h: 32 } },
  { id: "wall_base_lavender_C_c", label: "Wall Base: Lavender C Center", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 256, y: 160, w: 32, h: 32 } },
  { id: "wall_base_lavender_C_r", label: "Wall Base: Lavender C Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 288, y: 160, w: 32, h: 32 } },
  { id: "floor_preview_lavender_1", label: "Floor Preview: Lavender 1", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 320, y: 160, w: 32, h: 32 } },
  { id: "floor_preview_lavender_2", label: "Floor Preview: Lavender 2", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 352, y: 160, w: 32, h: 32 } },
  { id: "floor_preview_lavender_3", label: "Floor Preview: Lavender 3", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 160, w: 32, h: 32 } },
  { id: "floor_preview_lavender_4", label: "Floor Preview: Lavender 4", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 416, y: 160, w: 32, h: 32 } },
  { id: "floor_preview_lavender_5", label: "Floor Preview: Lavender 5", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 448, y: 160, w: 32, h: 32 } },
  { id: "floor_preview_lavender_6", label: "Floor Preview: Lavender 6", category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 480, y: 160, w: 32, h: 32 } },
  { id: "wall_lavender_B_l", label: "Wall Lavender B: Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 128, y: 224, w: 32, h: 32 } },
  { id: "wall_lavender_B_c", label: "Wall Lavender B: Center", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 160, y: 224, w: 32, h: 32 } },
  { id: "wall_lavender_B_r", label: "Wall Lavender B: Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 192, y: 224, w: 32, h: 32 } },
  { id: "divider_brick_gap", label: "Divider Pink: Gap", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 96, y: 352, w: 32, h: 32 } },
  { id: "divider_pink_gap", label: "Divider Pink: Gap", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 96, y: 384, w: 32, h: 32 } },
  { id: "divider_gray_gap_a", label: "Divider Gray: Gap A", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 96, y: 288, w: 32, h: 32 } },
  { id: "divider_brick_gap_a", label: "Divider Brick: Gap A", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 96, y: 320, w: 32, h: 32 } },
  { id: "wall_gray_B_l", label: "Wall Gray B: Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 128, y: 288, w: 32, h: 32 } },
  { id: "wall_gray_B_c", label: "Wall Gray B: Center", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 160, y: 288, w: 32, h: 32 } },
  { id: "wall_gray_B_r", label: "Wall Gray B: Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 192, y: 288, w: 32, h: 32 } },
  { id: "divider_lavender_gap", label: "Divider Lavender: Gap", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 96, y: 224, w: 32, h: 32 } },
  { id: "divider_gray_gap", label: "Divider Gray: Gap", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 96, y: 256, w: 32, h: 32 } },
  { id: "divider_outer_tl", label: "Divider: Outer Top-Left", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 32, y: 0, w: 32, h: 32 } },
  { id: "divider_outer_t", label: "Divider: Outer Top", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 64, y: 0, w: 32, h: 32 } },
  { id: "divider_outer_tr", label: "Divider: Outer Top-Right", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 96, y: 0, w: 32, h: 32 } },
  { id: "divider_outer_l", label: "Divider: Outer Left", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 128, y: 0, w: 32, h: 32 } },
  { id: "divider_door_t", label: "Divider: Door Top", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 256, y: 0, w: 32, h: 32 } },
  { id: "divider_window_tl", label: "Divider: Window Top-Left", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 320, y: 0, w: 32, h: 32 } },
  { id: "divider_window_t", label: "Divider: Window Top", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 352, y: 0, w: 32, h: 32 } },
  { id: "divider_window_tr", label: "Divider: Window Top-Right", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 0, w: 32, h: 32 } },
  { id: "divider_inner_bl", label: "Divider: Inner Bottom-Left", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 32, y: 32, w: 32, h: 32 } },
  { id: "divider_inner_b", label: "Divider: Inner Bottom", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 64, y: 32, w: 32, h: 32 } },
  { id: "divider_inner_br", label: "Divider: Inner Bottom-Right", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 96, y: 32, w: 32, h: 32 } },
  { id: "divider_cross", label: "Divider: Cross", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 128, y: 32, w: 32, h: 32 } },
  { id: "divider_t_right", label: "Divider: T-Right", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 160, y: 32, w: 32, h: 32 } },
  { id: "divider_t_left", label: "Divider: T-Left", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 192, y: 32, w: 32, h: 32 } },
  { id: "divider_horizontal", label: "Divider: Horizontal", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 224, y: 32, w: 32, h: 32 } },
  { id: "divider_door_fl", label: "Divider: Door Frame Left", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 256, y: 32, w: 32, h: 32 } },
  { id: "divider_door_fc", label: "Divider: Door Frame Center", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 288, y: 32, w: 32, h: 32 } },
  { id: "divider_window_c", label: "Divider: Window Center", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 352, y: 32, w: 32, h: 32 } },
  { id: "divider_window_mr", label: "Divider: Window Mid-Right", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 384, y: 32, w: 32, h: 32 } },
  { id: "divider_inner_tl", label: "Divider: Inner Top-Left", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 32, y: 64, w: 32, h: 32 } },
  { id: "divider_inner_t", label: "Divider: Inner Top", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 64, y: 64, w: 32, h: 32 } },
  { id: "divider_single", label: "Divider: Single", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 224, y: 64, w: 32, h: 32 } },
  { id: "divider_door_fbl", label: "Divider: Door Frame Bottom-Left", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 256, y: 64, w: 32, h: 32 } },
  { id: "divider_door_fb", label: "Divider: Door Frame Bottom", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 288, y: 64, w: 32, h: 32 } },
  { id: "divider_outer_b", label: "Divider: Outer Bottom", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 32, y: 96, w: 32, h: 32 } },
  { id: "divider_outer_br2", label: "Divider: Outer Bottom-Right 2", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 64, y: 96, w: 32, h: 32 } },
  { id: "divider_door_thl", label: "Divider: Door Threshold Left", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 256, y: 96, w: 32, h: 32 } },
  { id: "divider_door_th", label: "Divider: Door Threshold", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 288, y: 96, w: 32, h: 32 } },
  { id: "divider_vertical", label: "Divider: Vertical", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 224, y: 96, w: 32, h: 32 } },
  { id: "divider_t_down", label: "Divider: T-Down", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 160, y: 64, w: 32, h: 32 } },
  { id: "divider_outer_r_2h", label: "Divider: Outer Right 2-High", category: "divider", widthCells: 1, heightCells: 2, sprite: { x: 160, y: 64, w: 32, h: 64 } },
  { id: "divider_inner_tr", label: "Divider: Inner Top-Right", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 96, y: 64, w: 32, h: 32 } },
  { id: "divider_outer_r", label: "Divider: Outer Right", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 128, y: 64, w: 32, h: 32 } },
  { id: "divider_outer_bl", label: "Divider: Outer Bottom-Left", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 96, y: 96, w: 32, h: 32 } },
  { id: "divider_t_up", label: "Divider: T-Up", category: "divider", widthCells: 1, heightCells: 1, sprite: { x: 128, y: 96, w: 32, h: 32 } },
  { id: "divider_corner_block", label: "Divider: Corner Block 2x2", category: "divider", widthCells: 2, heightCells: 2, sprite: { x: 96, y: 64, w: 64, h: 64 } },
  { id: "divider_shadow_block", label: "Divider Shadow: Block 3x2", category: "divider", widthCells: 3, heightCells: 2, sprite: { x: 320, y: 64, w: 96, h: 64 } },
  { id: "wall_brick_B_l", label: "Wall Pink B: Left", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 128, y: 352, w: 32, h: 32 } },
  { id: "wall_brick_B_c", label: "Wall Pink B: Center", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 160, y: 352, w: 32, h: 32 } },
  { id: "wall_brick_B_r", label: "Wall Pink B: Right", category: "wall_tile", widthCells: 1, heightCells: 1, sprite: { x: 192, y: 352, w: 32, h: 32 } },
];

// ── 화이트/기본 바닥 타일 (16x16 단일 PNG 에셋) — 팔레트에서 직접 선택 가능 ────
const SIMPLE_FLOOR_TILES: FurnitureDef[] = [
  { id: "floor_white",      label: "화이트 바닥",   category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 0, w: 16, h: 16 }, sheetPath: "/assets/floors/floor_0.png" },
  { id: "floor_beige",      label: "베이지 바닥",   category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 0, w: 16, h: 16 }, sheetPath: "/assets/floors/floor_1.png" },
  { id: "floor_wood_light", label: "우드 라이트",    category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 0, w: 16, h: 16 }, sheetPath: "/assets/floors/floor_2.png" },
  { id: "floor_wood_dark",  label: "우드 다크",     category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 0, w: 16, h: 16 }, sheetPath: "/assets/floors/floor_3.png" },
  { id: "floor_tile_gray",  label: "타일 그레이",   category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 0, w: 16, h: 16 }, sheetPath: "/assets/floors/floor_4.png" },
  { id: "floor_carpet_blue",label: "카펫 블루",     category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 0, w: 16, h: 16 }, sheetPath: "/assets/floors/floor_5.png" },
  { id: "floor_carpet_red", label: "카펫 레드",     category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 0, w: 16, h: 16 }, sheetPath: "/assets/floors/floor_6.png" },
  { id: "floor_marble",     label: "마블",         category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 0, w: 16, h: 16 }, sheetPath: "/assets/floors/floor_7.png" },
  { id: "floor_checker",    label: "체커",         category: "floor_tile", widthCells: 1, heightCells: 1, sprite: { x: 0, y: 0, w: 16, h: 16 }, sheetPath: "/assets/floors/floor_8.png" },
];
FURNITURE_CATALOG.push(...SIMPLE_FLOOR_TILES);

const ROOM_BUILDER_TILES: FurnitureDef[] = ROOM_BUILDER_RAW.map(r => ({
  ...r,
  sheetPath: ROOM_BUILDER_SHEET,
  canPlaceOnWalls: true,
}));

const catalogMap = new Map([...FURNITURE_CATALOG, ...ROOM_BUILDER_TILES].map(f => [f.id, f]));

export function getFurnitureDef(id: string): FurnitureDef | undefined {
  return catalogMap.get(id);
}

export function getFurnitureByCategory(category: FurnitureCategory): FurnitureDef[] {
  return Array.from(catalogMap.values()).filter(f => f.category === category);
}

export function getAllFurniture(): FurnitureDef[] {
  return Array.from(catalogMap.values());
}

/** Update label and/or category of a furniture item, persisted to localStorage */
export function updateFurnitureMeta(
  id: string,
  updates: { label?: string; category?: FurnitureCategory },
): void {
  const def = catalogMap.get(id);
  if (!def) return;
  const updated = { ...def, ...updates };
  catalogMap.set(id, updated);
  const idx = FURNITURE_CATALOG.findIndex((f) => f.id === id);
  if (idx >= 0) FURNITURE_CATALOG[idx] = updated;
  _saveOverrides();
  try { syncFurnitureOverridesToServer(); } catch {}
}

// --- Persistence helpers ---
const OVERRIDES_KEY = "teammaker-furniture-overrides";

interface FurnitureOverride {
  label?: string;
  category?: FurnitureCategory;
  deleted?: boolean;
}

// 관리자가 숨긴 아이템 id 집합 (localStorage 기반)
const _hiddenIds = new Set<string>();

export function isHiddenFurniture(id: string): boolean {
  return _hiddenIds.has(id);
}

export function getVisibleFurnitureList(): FurnitureDef[] {
  return Array.from(catalogMap.values()).filter(f => !_hiddenIds.has(f.id));
}

/** 관리자 삭제: 팔레트에서 숨김 처리(복구는 restoreFurniture) */
export function deleteFurniture(id: string): void {
  _hiddenIds.add(id);
  _saveOverrides();
  try { syncFurnitureOverridesToServer(); } catch {}
}

/** 관리자 복구: 삭제된 아이템 다시 노출 */
export function restoreFurniture(id: string): void {
  _hiddenIds.delete(id);
  _saveOverrides();
  try { syncFurnitureOverridesToServer(); } catch {}
}

function _saveOverrides(): void {
  if (typeof window === "undefined") return;
  const overrides: Record<string, FurnitureOverride> = {};
  for (const [id, def] of catalogMap) {
    const orig = _originalMap.get(id);
    if (!orig) continue;
    const o: FurnitureOverride = {};
    if (def.label !== orig.label) o.label = def.label;
    if (def.category !== orig.category) o.category = def.category;
    if (_hiddenIds.has(id)) o.deleted = true;
    if (Object.keys(o).length > 0) overrides[id] = o;
  }
  // 원본에 없는 id 도 숨김 가능성 있음 (향후 확장)
  for (const id of _hiddenIds) {
    if (!overrides[id]) overrides[id] = { deleted: true };
  }
  if (Object.keys(overrides).length > 0) {
    localStorage.setItem(OVERRIDES_KEY, JSON.stringify(overrides));
  } else {
    localStorage.removeItem(OVERRIDES_KEY);
  }
}

function _loadOverrides(): void {
  if (typeof window === "undefined") return;
  try {
    const raw = localStorage.getItem(OVERRIDES_KEY);
    if (!raw) return;
    const overrides: Record<string, FurnitureOverride> = JSON.parse(raw);
    for (const [id, o] of Object.entries(overrides)) {
      if (o.deleted) _hiddenIds.add(id);
      const def = catalogMap.get(id);
      if (!def) continue;
      const { deleted: _d, ...rest } = o;
      const updated = { ...def, ...rest };
      catalogMap.set(id, updated);
      const idx = FURNITURE_CATALOG.findIndex((f) => f.id === id);
      if (idx >= 0) FURNITURE_CATALOG[idx] = updated;
    }
  } catch { /* ignore corrupt data */ }
}

// Keep a snapshot of originals for diffing
const _originalMap = new Map(catalogMap);

// Load overrides on module init
_loadOverrides();

// ── 서버 동기화 (모든 관리자 기기 공유) ─────────────────
function _apiBase(): string {
  if (typeof window === "undefined") return "";
  const h = window.location.hostname;
  const isLocal = h === "localhost" || h === "127.0.0.1" || h.endsWith(".local") || h.startsWith("192.168.");
  return isLocal ? `http://${h}:8000` : "https://api.600g.net";
}

const POKE_LABEL_KEY = "hq-poke-label-overrides";
const POKE_HIDDEN_KEY = "hq-poke-hidden";
const TILE_LABEL_KEY = "hq-tile-label-overrides";
const TILE_HIDDEN_KEY = "hq-tile-hidden";

function _applyServerOverrides(serverOverrides: Record<string, FurnitureOverride>): void {
  if (typeof window === "undefined") return;
  // 1) 카탈로그 정의 업데이트
  for (const [id, o] of Object.entries(serverOverrides)) {
    if (o.deleted) _hiddenIds.add(id); else _hiddenIds.delete(id);
    const def = catalogMap.get(id);
    if (!def) continue;
    const { deleted: _d, ...rest } = o;
    const updated = { ...def, ...rest };
    catalogMap.set(id, updated);
    const idx = FURNITURE_CATALOG.findIndex((f) => f.id === id);
    if (idx >= 0) FURNITURE_CATALOG[idx] = updated;
  }
  // 2) localStorage 미러 (오프라인에서도 즉시 반영되게)
  _saveOverrides();
}

/** 서버에서 오버라이드 받아와 적용. 앱 부팅 시 + 관리자가 편집기 열 때 호출. */
export async function fetchAndApplyFurnitureOverrides(): Promise<void> {
  if (typeof window === "undefined") return;
  try {
    const res = await fetch(`${_apiBase()}/api/furniture/overrides`, { cache: "no-store" });
    if (!res.ok) { console.warn("[hq-furn] fetch failed", res.status); return; }
    const j = await res.json();
    const data = j?.overrides;
    if (!data) return;
    // 포맷: {"version":1, "overrides":{...}, "poke_labels":{...}, "poke_hidden":[...]}
    const overrides = data.overrides || {};
    const count = Object.keys(overrides).length;
    console.info(`[hq-furn] overrides fetched: ${count} items`);
    _applyServerOverrides(overrides);
    // poke
    if (data.poke_labels && typeof data.poke_labels === "object") {
      try { localStorage.setItem(POKE_LABEL_KEY, JSON.stringify(data.poke_labels)); } catch {}
    }
    if (Array.isArray(data.poke_hidden)) {
      try { localStorage.setItem(POKE_HIDDEN_KEY, JSON.stringify(data.poke_hidden)); } catch {}
    }
    // tile
    if (data.tile_labels && typeof data.tile_labels === "object") {
      try { localStorage.setItem(TILE_LABEL_KEY, JSON.stringify(data.tile_labels)); } catch {}
    }
    if (Array.isArray(data.tile_hidden)) {
      try { localStorage.setItem(TILE_HIDDEN_KEY, JSON.stringify(data.tile_hidden)); } catch {}
    }
    if (typeof window !== "undefined") {
      window.dispatchEvent(new CustomEvent("hq:furniture-overrides-applied"));
    }
  } catch { /* ignore */ }
}

let _syncDebounce: ReturnType<typeof setTimeout> | null = null;

/** 현재 오버라이드를 서버에 저장 (디바운스). 관리자만 성공 유효. */
export function syncFurnitureOverridesToServer(): void {
  if (typeof window === "undefined") return;
  if (_syncDebounce) clearTimeout(_syncDebounce);
  _syncDebounce = setTimeout(async () => {
    // 현재 override 상태 수집
    const overrides: Record<string, FurnitureOverride> = {};
    for (const [id, def] of catalogMap) {
      const orig = _originalMap.get(id);
      if (!orig) continue;
      const o: FurnitureOverride = {};
      if (def.label !== orig.label) o.label = def.label;
      if (def.category !== orig.category) o.category = def.category;
      if (_hiddenIds.has(id)) o.deleted = true;
      if (Object.keys(o).length > 0) overrides[id] = o;
    }
    for (const id of _hiddenIds) if (!overrides[id]) overrides[id] = { deleted: true };
    // 포켓몬/타일 (localStorage → 서버)
    const readJson = <T>(key: string, fallback: T): T => {
      try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) as T : fallback; }
      catch { return fallback; }
    };
    const pokeLabels = readJson<Record<string, string>>(POKE_LABEL_KEY, {});
    const pokeHidden = readJson<string[]>(POKE_HIDDEN_KEY, []);
    const tileLabels = readJson<Record<string, string>>(TILE_LABEL_KEY, {});
    const tileHidden = readJson<string[]>(TILE_HIDDEN_KEY, []);
    try {
      await fetch(`${_apiBase()}/api/furniture/overrides`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          overrides,
          poke_labels: pokeLabels, poke_hidden: pokeHidden,
          tile_labels: tileLabels, tile_hidden: tileHidden,
        }),
      });
    } catch { /* 오프라인이어도 localStorage는 이미 반영됨 */ }
  }, 600);
}

// 서버 overrides 동기화 (이름 변경/카테고리/숨김) — 이전 ui/ 에서 편집한 내역 복구용
//  · 부팅 시 1회 fetch (기기 간 공유 + localStorage 보강)
//  · 그 후는 필요 시 수동 호출 (polling 비활성화 — 토큰/요청 절약)
if (typeof window !== "undefined") {
  setTimeout(() => {
    fetchAndApplyFurnitureOverrides().catch(() => { /* 서버 없어도 localStorage 로 동작 */ });
  }, 500);
  document.addEventListener("visibilitychange", () => {
    if (document.visibilityState === "visible") {
      fetchAndApplyFurnitureOverrides().catch(() => {});
    }
  });
}

/** Export current overrides as JSON string (for applying to source code) */
export function exportOverrides(): string | null {
  const overrides: Record<string, FurnitureOverride> = {};
  for (const [id, def] of catalogMap) {
    const orig = _originalMap.get(id);
    if (!orig) continue;
    const o: FurnitureOverride = {};
    if (def.label !== orig.label) o.label = def.label;
    if (def.category !== orig.category) o.category = def.category;
    if (Object.keys(o).length > 0) overrides[id] = o;
  }
  if (Object.keys(overrides).length === 0) return null;
  return JSON.stringify(overrides, null, 2);
}

/** Get the count of current overrides */
export function getOverrideCount(): number {
  let count = 0;
  for (const [id, def] of catalogMap) {
    const orig = _originalMap.get(id);
    if (!orig) continue;
    if (def.label !== orig.label || def.category !== orig.category) count++;
  }
  return count;
}
