import JSZip from "jszip";
import type { Session } from "@/types/session";
import type { Artifact } from "@/types/artifact";
import type { ChatMessage } from "@/types/chat";

export interface DownloadLabels {
  untitled: string;
  sessionFallback: string;
  created: string;
  request: string;
  result: string;
}

export function sessionToMarkdown(session: Session, locale: string, labels: DownloadLabels): string {
  const date = new Date(session.createdAt).toLocaleString(locale);
  const lines: string[] = [
    `# ${session.title || labels.untitled}`,
    `> ${labels.created}: ${date}`,
    "",
  ];

  for (const msg of session.messages) {
    const time = new Date(msg.timestamp).toLocaleTimeString(locale);
    if (msg.type === "user") {
      lines.push(`## ${labels.request} (${time})`, "", msg.content, "");
    } else if (msg.type === "ai") {
      const from = msg.agentName ? ` — ${msg.agentName}` : "";
      lines.push(`## ${labels.result}${from} (${time})`, "", msg.content, "");
    }
  }

  return lines.join("\n");
}

export function downloadAsMarkdown(session: Session, locale: string, labels: DownloadLabels): void {
  const content = sessionToMarkdown(session, locale, labels);
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${session.title || labels.sessionFallback}-${session.id.slice(0, 8)}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

function artifactFilename(artifact: Artifact): string {
  if (artifact.type === "code") return artifact.title;
  if (artifact.title.endsWith(".md")) return artifact.title;
  return `${artifact.title}.md`;
}

export async function downloadArtifactsAsZip(
  artifacts: Artifact[],
  zipName: string
): Promise<void> {
  const zip = new JSZip();

  for (const artifact of artifacts) {
    zip.file(artifactFilename(artifact), artifact.content);
  }

  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${zipName}.zip`;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadSingleArtifact(artifact: Artifact): void {
  const blob = new Blob([artifact.content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = artifactFilename(artifact);
  a.click();
  URL.revokeObjectURL(url);
}

export async function saveArtifactsToDisk(
  artifacts: Artifact[],
  preselectedDir?: string | null,
  promptMessage?: string
): Promise<string | null> {
  let dir = preselectedDir || null;

  if (!dir) {
    dir = prompt(promptMessage ?? "Enter the directory path to save artifacts:");
  }
  if (!dir) return null;

  await fetch("/api/fs/save-artifacts", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      dirPath: dir,
      artifacts: artifacts.map((a) => ({
        title: artifactFilename(a),
        content: a.content,
        type: a.type,
        language: a.language,
      })),
    }),
  });

  return dir;
}

export async function downloadAllPipelineArtifacts(
  messages: ChatMessage[],
  zipName: string
): Promise<void> {
  const zip = new JSZip();

  const agentMessages = messages.filter(
    (m) => m.type === "ai" && m.artifacts && m.artifacts.length > 0
  );

  if (agentMessages.length === 0) return;

  // Process in pipeline order — later agents overwrite same filename (latest wins)
  const fileMap = new Map<string, { content: string; agentName?: string }>();

  for (const msg of agentMessages) {
    for (const artifact of msg.artifacts!) {
      const filename = artifactFilename(artifact);
      // Code artifacts go to project root; documents/action items go to docs/ folder
      const path =
        artifact.type === "code" ? filename : `docs/${filename}`;
      fileMap.set(path, { content: artifact.content, agentName: msg.agentName });
    }
  }

  for (const [path, { content }] of fileMap) {
    zip.file(path, content);
  }

  // Generate README.md — project structure and per-agent contribution summary
  const agentNames = agentMessages
    .map((m) => m.agentName)
    .filter((n): n is string => !!n);
  const uniqueAgents = [...new Set(agentNames)];
  const fileList = [...fileMap.keys()].sort();
  const pipelineLabel = uniqueAgents.length > 0
    ? `${uniqueAgents.join(" → ")} pipeline`
    : "pipeline";

  const readme = [
    `# ${zipName}`,
    "",
    `> Generated by ${pipelineLabel}`,
    "",
    "## Project Structure",
    "",
    "```",
    ...fileList.map((f) => f),
    "```",
    "",
  ].join("\n");

  if (!fileMap.has("README.md")) {
    zip.file("README.md", readme);
  }

  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${zipName}.zip`;
  a.click();
  URL.revokeObjectURL(url);
}
