// TM 가구 영문 라벨 → 한글 번역 (자주 쓰이는 것)
// 전체 번역이 아니라 있는 것만 매핑. 없으면 원문 표시.
export const LABEL_KO: Record<string, string> = {
  // desk
  "Desk Top (Tan)": "책상(탄)",
  "Desk Top (Beige)": "책상(베이지)",
  "Desk Top (Orange)": "책상(오렌지)",
  "Desk Top (Wood)": "책상(나무)",
  "Desk Top (Lavender)": "책상(라벤더)",
  "Desk L-Shape (Orange)": "L자 책상(오렌지)",
  "Desk Bottom (Wood)": "책상 하단(나무)",
  "Desk Module (A)": "프린터(작)A",
  "Desk Module (B)": "프린터(작)B",
  "Desk Module (C)": "프린터(작)C",
  "Desk Module (D)": "프린터(중)D",
  "Desk Module (E)": "프린터(중)E",
  "Dual Workstation": "노트북 세트",
  "Mouse & Pad": "듀얼 모니터(대)",
  "Floor Lamp": "스탠드(데스크)",
  "Globe on Stand": "지구본(데스크)",
  "Coat Rack": "옷걸이(데스크)",
  "Briefcase": "서류 가방",
  "Desk Side (Beige)": "책상 옆(베이지)",
  "Desk Side (Tan)": "책상 옆(탄)",
  "Desk Side (Lavender)": "책상 옆(라벤더)",
  "Desk Extension (Lavender A)": "프린터A",
  "Desk Extension (Lavender B)": "프린터B",
  "Desk Extension (Lavender C)": "프린터C",
  "Desk with PC": "컴퓨터(책상위)",
  "Desk with Monitors": "듀얼 컴퓨터(책상위)",
  "Corner Workstation": "코너 컴퓨터",
  "Workstation (Large)": "커피포트",
  "Binder Set": "모니터 암(바인더)",
  "Tall Cabinet (A)": "모니터 암A",
  "Tall Cabinet (B)": "모니터 암B",
  "Conference Table End": "모니터암(원형)",
  "Conference Table (Beige)": "회의 테이블(베)",
  "Conference Table (Brown)": "회의 테이블(갈)",
  "Conference Table (Lavender)": "회의 테이블(라)",
  "Conference Table (Tan)": "회의 테이블(탄)",
  "Desk Lamp": "데스크 램프",
  "Desk Phone (A)": "전화기A",
  "Desk Phone (B)": "전화기B",
  "Desk Phone (C)": "전화기C",
  "Desk Phone (D)": "전화기D",
  "Cubicle Desk (Beige)": "큐비클 책상(베이지)",
  "Cubicle Desk (Tan)": "큐비클 책상(탄)",
  "Cubicle Desk (Gray)": "큐비클 책상(회색)",
  "Cubicle Desk (Yellow)": "큐비클 책상(노랑)",
  "Cubicle Desk (Lavender)": "큐비클 책상(라벤더)",
  "Cubicle Panel Narrow (Beige)": "큐비클 패널(베이지)",
  "Cubicle Panel Narrow (Gray)": "큐비클 패널(회색)",
  "Cubicle Panel Narrow (Lavender)": "큐비클 패널(라벤더)",
  "L-Desk (Brown)": "L자 책상(갈)",
  "L-Desk (Beige)": "L자 책상(베이지)",
  // chair
  "Office Chair Back (Dark)": "의자 뒤(어두움)",
  "Office Chair Front (Dark)": "의자 앞(어두움)",
  "Office Chair Front (Check)": "의자 앞(체크)",
  "Office Chair Front (Brown)": "의자(갈)",
  "Office Chair Front (Brown - Check)": "의자(갈·체크)",
  "Office Chair Front-Left (Brown)": "의자 좌앞(갈)",
  "Office Chair Front-Right (Brown)": "의자 우앞(갈)",
  "Office Chair Front-Left (Dark)": "의자 좌앞(어두움)",
  "Office Chair Left": "의자 좌",
  "Office Chair Right": "의자 우",
  "Office Chair Left 2": "의자 좌2",
  "Office Chair Brown Left 2": "의자 좌2(갈)",
  "Office Chair Left (Brown)": "의자 좌(갈)",
  "Office Chair Right (Brown)": "의자 우(갈)",
  "Office Stool": "문서(책상위)",
  "Floor Cushion Set": "서류(책상위)",
  "Swivel Chair (Blue)": "회전의자(파)",
  "Swivel Chair (Green)": "회전의자(초)",
  "Swivel Chair (Yellow)": "회전의자(노)",
  "Swivel Chair (Gold)": "회전의자(금)",
  // sofa / seating
  "Sofa": "소파",
  "Bench": "벤치",
  // storage
  "Book Shelf Row (A)": "책꽂이A",
  "Book Shelf Row (B)": "책꽂이B",
  "Filing Cabinet (Side)": "파일 캐비닛",
  "Filing Cabinet (Dark B)": "파일 캐비닛(어두)",
  // plant
  "Potted Plant (Tall)": "화분(큰)",
  "Potted Plant (Round)": "화분(둥근)",
  "Potted Plant (Bushy)": "화분(풀)",
  // appliance
  "Dual Monitor Setup": "듀얼 모니터",
  "Monitor": "모니터",
  "Monitor (Small)": "작은 모니터",
  "Printer (Small)": "프린터(소)",
  "Printer (Large)": "프린터(대)",
  "PC Tower (Beige)": "PC 타워(베)",
  "PC Tower (Gray)": "PC 타워(회)",
  "PC Tower (Dark)": "PC 타워(어)",
  "Keyboard": "키보드",
  // accessory
  "Pen Holder": "펜꽂이",
  "Pen (A)": "펜A",
  "Pen (B)": "펜B",
  "Coffee Cup": "커피잔",
  // floor_decor
  "Backpack (Blue)": "가방(파)",
  "Backpack (Orange)": "가방(주)",
  "Backpack (Brown)": "가방(갈)",
  "Suitcase (Blue)": "캐리어(파)",
  "Suitcase (Red)": "캐리어(빨)",
  "Suitcase (Orange)": "캐리어(주)",
  "Suitcase (Brown)": "캐리어(갈)",
  "Suitcase (Teal)": "캐리어(청)",
  "Suitcase (Green)": "캐리어(초)",
  "Trash Can (Gray)": "배낭(회)",
  "Trash Can (Blue)": "배낭(파)",
  "Trash Can (Green)": "배낭(초)",
  "Trash Can (Brown)": "배낭(갈)",
  // wall decor
  "Wall Art (Colorful)": "벽 포스터(컬러)",
  "Wall Art (Sunset)": "벽 포스터(석양)",
  // board
  "Whiteboard": "화이트보드",
  // misc
  "Dispenser Full 2": "정수기",
};

export function toKoreanLabel(eng: string | undefined): string {
  if (!eng) return "";
  return LABEL_KO[eng] || eng;
}
